### ISSUE TITLE
Serious Bug That Avoids Log-In - Please Fix ASAP

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#184]
java.lang.IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1101) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:259) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:366) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:283) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-23 13:16:13.317 [qtp988786279-211] ERROR io.javalin.Javalin - Exception occurred while servicing http-request
java.lang.IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1101) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:259) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:366) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:283) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-23 13:16:13.324 [qtp988786279-225] ERROR io.javalin.Javalin - Exception occurred while servicing http-request
java.lang.IllegalStateException: Unexpected wrap result BUFFER_OVERFLOW
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1101) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:259) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:366) ~[jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:283) ~[http2-common-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1507) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:132) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-23 13:16:42.658 [qtp988786279-101] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(776219d5-b9d5-4871-9096-f8eeb3dcd7db), user=somhunter, session=node05asioi0t6ova1bfy1wafl5r4t19, api=REST)
2020-10-23 13:29:03.173 [qtp988786279-231] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(5451ab15-04e7-44e9-a56c-22e6f6661fbd), user=somhunter, session=node01acj0si15w75d1dg6cv9yudoof115525, api=REST)
2020-10-23 13:47:54.646 [qtp988786279-180] INFO dev.dres.api.rest.types.status.ErrorStatusException$Companion - ErrorStatusException with code 404 and message 'There is currently no eligible competition with an active task.' thrown by dev.dres.api.rest.handler.SubmissionHandler.getActiveRun-KjL0c2s(SubmissionHandler.kt:57) for request from 87.116.5.66
2020-10-23 15:42:48.907 [qtp988786279-273] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(2db662e1-9923-4de5-af68-d2be98e4c752), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:02:45.379 [qtp988786279-273] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(2ceabd6b-11b9-4b7c-a5bb-839e12cac0be), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:02:49.298 [qtp988786279-286] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(a5acebcb-283d-4784-9618-bd8463e3aeb2), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:03:34.607 [qtp988786279-276] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(f687b393-974a-412a-9654-a7c9155dfdae), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:06:07.893 [qtp988786279-271] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(c3ecb959-c664-4c31-a13d-e3bce37a6069), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:08:50.010 [qtp988786279-276] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(3c2be1b7-dd34-4ded-b109-b215efdae800), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:09:37.052 [qtp988786279-271] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(ce540e06-7183-4e7c-ad10-c8ba4e04d1df), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:09:55.761 [qtp988786279-285] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(720c83d9-23cf-4e7b-b65e-b6b667130bbb), user=somhunter, session=node01b8t3qdjefyzflj3pftnethaj134141, api=REST)
2020-10-23 16:23:40.969 [qtp988786279-276] INFO dev.dres.run.audit.AuditLogger - Audit event: LoginAuditLogEntry(id=UID(176d4355-5df2-4276-aaba-d33d44f0238a), user=first, session=node0d4gc7joxpl6ikrv2m7hoqn3b12099, api=REST)
2020-10-23 16:54:12.434 [qtp988786279-273] INFO dev.dres.api.rest.types.status.ErrorStatusException$Companion - ErrorStatusException with code 404 and message 'There is currently no eligible competition with an active task.' thrown by dev.dres.api.rest.handler.SubmissionHandler.getActiveRun-KjL0c2s(SubmissionHandler.kt:57) for request from 115.72.239.130
2020-10-23 16:56:24.386 [qtp988786279-276] INFO dev.dres.api.rest.types.status.ErrorStatusException$Companion - ErrorStatusException with code 404 and message 'There is currently no eligible competition with an active task.' thrown by dev.dres.api.rest.handler.SubmissionHandler.getActiveRun-KjL0c2s(SubmissionHandler.kt:57) for request from 115.72.239.130
2020-10-23 17:02:04.817 [qtp988786279-288] INFO dev.dres.api.rest.types.status.ErrorStatusException$Companion - ErrorStatusException with code 404 and message 'There is currently no eligible competition with an active task.' thrown by dev.dres.api.rest.handler.SubmissionHandler.getActiveRun-KjL0c2s(SubmissionHandler.kt:57) for request from 115.72.239.130

**Comment by lucaro** [comment]
These stack traces all come from the jetty server and are not directly generated by any DRES logic. What I can see here is that there are a lot of login attempts from 'somhunter', so they certainly generate unnecessary load. This is probably not the issue though.

**Comment by lucaro** [comment]
Looks to be related to https://github.com/eclipse/jetty.project/issues/5006

**Comment by sauterl** [comment]
Ideally, we could see more of the log, as the snipped above is from October 23 13.16h to 17.02h
