### ISSUE TITLE
FFprobe missing in ext/ in ubuntu

### ISSUE THREAD

**Issue by cristinailli** [dres-dev/DRES#198]
Using the gradle command ./gradlew setupFFMpeg no FFprobe is missing in the ext/ folder on ubuntu 18.04.
After some research I found the probably correct URL: https://github.com/vot/ffbinaries-prebuilt/releases/download/v4.2.1/ffprobe-4.2.1-linux-64.zip

I stumbled upon this issue because I followed the README, created the collection & wanted to scan the video files when the following error occurred:

```DRES> collection scan -c V3C1 -vt mp4
found /tank/V3C1/video/v_00272.mp4
Analyzing /tank/V3C1/video/v_00272.mp4
java.lang.RuntimeException: Failed to start process.
        at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:87)
        at com.github.kokorin.jaffree.ffprobe.FFprobe.execute(FFprobe.java:447)
        at dev.dres.utilities.FFmpegUtil.analyze(FFmpegUtil.kt:145)
        at dev.dres.utilities.FFmpegUtil.analyze$default(FFmpegUtil.kt:140)
        at dev.dres.api.cli.MediaCollectionCommand$ScanCollectionCommand.run(MediaCollectionCommand.kt:277)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at dev.dres.api.cli.Cli.loop(Cli.kt:70)
        at dev.dres.DRES.main(DRES.kt:56)
Caused by: java.io.IOException: Cannot run program "ext/ffmpeg/ffprobe": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:83)
        ... 12 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 14 more
DRES>
Exception in thread "main" org.jline.reader.EndOfFileException
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:643)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
        at dev.dres.api.cli.Cli.loop(Cli.kt:57)
        at dev.dres.DRES.main(DRES.kt:56)```

**Comment by lucaro** [comment]
Thanks, the whole ffmpeg setup process has quite a bit of room for improvement. Hopefully, we can address this issue in its next iteration as well...
